# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-18 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantry_tracker', '0002_auto_20181117_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_grocery_list', to='pantry_tracker.Product'),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_grocery_list', to='pantry_tracker.User'),
        ),
    ]
