# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-18 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantry_tracker', '0003_auto_20181118_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ManyToManyField(related_name='added_recipes', to='pantry_tracker.User')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_submitted', to='pantry_tracker.User')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('note', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='please link to static img', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='measure',
            field=models.CharField(default='unit', max_length=255),
        ),
        migrations.AddField(
            model_name='recipecomponents',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_recipe', to='pantry_tracker.Product'),
        ),
        migrations.AddField(
            model_name='recipecomponents',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='pantry_tracker.Recipe'),
        ),
    ]
