# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-19 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry_tracker', '0004_auto_20181118_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='shelf_life',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
