# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-19 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry_tracker', '0005_auto_20181119_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
