# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-19 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry_tracker', '0005_user_access_level'),
        ('pantry_tracker', '0006_product_product_category'),
    ]

    operations = [
    ]
