# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-19 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry_tracker', '0008_auto_20181119_1517'),
        ('pantry_tracker', '0007_merge_20181119_1544'),
        ('pantry_tracker', '0007_merge_20181119_1604'),
    ]

    operations = [
    ]
