# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-20 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry_tracker', '0009_merge_20181119_1738'),
        ('pantry_tracker', '0009_merge_20181119_2258'),
    ]

    operations = [
    ]
