# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-20 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry_tracker', '0011_auto_20181120_1058'),
        ('pantry_tracker', '0011_auto_20181120_0130'),
    ]

    operations = [
    ]
