# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-20 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantry_tracker', '0012_auto_20181120_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_grocery_list', to='pantry_tracker.User'),
        ),
    ]
