# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-20 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry_tracker', '0013_auto_20181120_1936'),
        ('pantry_tracker', '0015_product_diet_flag'),
    ]

    operations = [
    ]
