# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-20 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry_tracker', '0017_auto_20181120_2141'),
        ('pantry_tracker', '0016_merge_20181120_2154'),
        ('pantry_tracker', '0016_merge_20181120_1538'),
    ]

    operations = [
    ]
