# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry_tracker', '0018_merge_20181120_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gluten_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lactose_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vegetarian',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='diet',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
