# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry_tracker', '0020_merge_20181121_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='diet',
        ),
    ]
