# Generated by Django 2.1.5 on 2019-02-07 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantry_tracker', '0021_remove_user_diet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_grocery_list', to='pantry_tracker.User'),
        ),
        migrations.AlterField(
            model_name='recipecomponents',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipe', to='pantry_tracker.Product'),
        ),
        migrations.AlterField(
            model_name='recipecomponents',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='pantry_tracker.Recipe'),
        ),
    ]
